# Generated by Django 3.2.25 on 2024-04-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dish_pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
